/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lee_ndkdemonativesqlite_util_JniUtil */

#ifndef _Included_com_example_lee_ndkdemonativesqlite_util_JniUtil
#define _Included_com_example_lee_ndkdemonativesqlite_util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lee_ndkdemonativesqlite_util_JniUtil
 * Method:    getDataBaseResultList
 * Signature: (Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_example_lee_ndkdemonativesqlite_util_JniUtil_getDataBaseResultList
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
